#!/bin/bash

# obtain new files
scp operator@daqman.starp.bnl.gov:/home/operator/fmshv/hvlog_run16/history_* ./

if [ $# -eq 2 ]; then
  month=$1
  day=$2
elif [ $# -eq 0 ]; then
  month=$(date +%-m)
  day=$(date +%-d)
else
  echo "Usage: $0 [month] [day]"
  exit
fi


> master
cat history_*${month}.${day} >> master

root -b -q 'mk_tree.C("master",'${month}','${day}',0,0)'

touch monitor.pdf; rm monitor.pdf
touch summary.pdf; rm summary.pdf
touch rootfile.root; rm rootfile.root

ln -sv monitor.2015.${month}.${day}.pdf monitor.pdf
ln -sv summary.2015.${month}.${day}.pdf summary.pdf
ln -sv rootfile.2015.${month}.${day}.root rootfile.root
